services:
  db:
    image: postgres:latest
    container_name: streamflex_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: streamflex_redis
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    container_name: streamflex_backend

    volumes:
      - .:/app
      - streamflex_media:/app/media
      - streamflex_static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
  redis_data:
  streamflex_media:
  streamflex_static:
